# Generated by Django 4.1.5 on 2023-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This is the name to appear in the frontend', max_length=30, verbose_name='My Name:')),
                ('phone', models.IntegerField(help_text='My contact phone number', verbose_name='My phone number:')),
                ('email', models.EmailField(help_text='My contact email', max_length=254, verbose_name='My Email:')),
                ('description', models.TextField(help_text='A little details about me', verbose_name='A brief description:')),
                ('image', models.ImageField(help_text='An image of me', upload_to='', verbose_name='Image')),
            ],
        ),
    ]
