# Generated by Django 4.1.5 on 2023-01-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_me',
            options={'verbose_name': 'Introduction - About me'},
        ),
    ]
