# Generated by Django 4.1.5 on 2023-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_alter_about_me_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender sending an email', max_length=255, verbose_name='Name of Sender')),
                ('email', models.EmailField(help_text='Contact email of the sender', max_length=254, verbose_name='Email of Sender')),
                ('message', models.TextField(help_text='Message received', verbose_name='Content Message:')),
            ],
            options={
                'verbose_name': 'My Contact Message',
                'verbose_name_plural': 'My Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The image of each project', upload_to='', verbose_name='My Project Image')),
                ('title', models.CharField(help_text='Title of each project', max_length=255, verbose_name='My Project title')),
                ('link', models.URLField(help_text='Links to urls', verbose_name='Urls Link')),
            ],
            options={
                'verbose_name': 'My Project',
                'verbose_name_plural': 'My Projects',
            },
        ),
    ]
